开始训练...
=============
=============
0
Traceback (most recent call last):
  File "D:/Users/Admin/PycharmProjects/PyCharm_Projects/Deep_learning/cat_dog/model_training02.py", line 115, in <module>
    train(model, EPOCH_NLM, opt)
  File "D:/Users/Admin/PycharmProjects/PyCharm_Projects/Deep_learning/cat_dog/model_training02.py", line 38, in train
    logits = model(img)
  File "D:\Users\Admin\Python37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Users\Admin\PycharmProjects\PyCharm_Projects\Deep_learning\cat_dog\LeNet.py", line 41, in forward
    input = paddle.reshape(input, shape=[2, 3, 100, 100])  # 转换维度
  File "D:\Users\Admin\Python37\lib\site-packages\paddle\tensor\manipulation.py", line 1582, in reshape
    return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
  File "D:\Users\Admin\Python37\lib\site-packages\paddle\fluid\layers\nn.py", line 6142, in reshape
    out, _ = core.ops.reshape2(x, None, 'shape', shape)
ValueError: (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 3, 100, 100], X's size = 30000, 'shape' is [2, 3, 100, 100], the capacity of 'shape' is 60000.
  [Hint: Expected capacity == in_size, but received capacity:60000 != in_size:30000.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/reshape_op.cc:222)
  [operator < reshape2 > error]
